// <auto-generated />
using EventsManagement_Chayma.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventsManagement_Chayma.Migrations
{
    [DbContext(typeof(EventsClientDbContext))]
    [Migration("20231221135514_participant_mig")]
    partial class participant_mig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventsManagement_Chayma.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Event__3214EC07044FA894");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Event", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description 1",
                            EndDate = "15/02/2023",
                            Location = "Location 1",
                            OrganizerId = 2,
                            StartDate = "15/02/2023",
                            Title = "Event 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            EndDate = "15/02/2023",
                            Location = "Location 2",
                            OrganizerId = 3,
                            StartDate = "15/02/2023",
                            Title = "Event 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description 3",
                            EndDate = "15/02/2023",
                            Location = "Location 3",
                            OrganizerId = 1,
                            StartDate = "15/02/2023",
                            Title = "Event 3"
                        });
                });

            modelBuilder.Entity("EventsManagement_Chayma.Models.Organizer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("PK__Organize__3214EC071E02B1E5");

                    b.ToTable("Organizer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "email1@gmail.com",
                            Name = "Organizer 1",
                            Phone = "255 641"
                        },
                        new
                        {
                            Id = 2,
                            Email = "email2@gmail.com",
                            Name = "Organizer 2",
                            Phone = "255 641"
                        },
                        new
                        {
                            Id = 3,
                            Email = "email3@gmail.com",
                            Name = "Organizer 3",
                            Phone = "255 641"
                        });
                });

            modelBuilder.Entity("EventsManagement_Chayma.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("EventsManagement_Chayma.Models.Event", b =>
                {
                    b.HasOne("EventsManagement_Chayma.Models.Organizer", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .IsRequired()
                        .HasConstraintName("FK_Event_Org");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("EventsManagement_Chayma.Models.Organizer", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
